#
# kakrc
#

set global indentwidth 2
colorscheme nord
hook global WinCreate .* %{add-highlighter window number_lines}
add-highlighter global/ wrap -width 101 -indent -word
set-option global ui_options ncurses_assistant=none
set-face global GitBlame 'rgb:D8DEE9'

#
# kakoune-cd extension
# https://github.com/Delapouite/kakoune-cd
#
map global goto d '<esc>:change-directory-current-buffer<ret>' -docstring 'current buffer dir'
map global goto r '<esc>:change-directory-project-root<ret>' -docstring 'project root dir'
map global goto p '<esc>:cd ..;print-working-directory<ret>' -docstring 'parent dir'
map global user e ':edit-current-buffer-directory<ret>' -docstring 'edit in current buffer dir'
alias global cdd change-directory-current-buffer
alias global cdr change-directory-project-root
alias global pwd print-working-directory
alias global ecd edit-current-buffer-directory

#
# kakoune-buffers extension
# https://github.com/Delapouite/kakoune-buffers
#
map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
alias global bd delete-buffer
alias global bf buffer-first
alias global bl buffer-last
alias global bo buffer-only
alias global bo! buffer-only-force

#
# kakoune-i3 extension
# https://github.com/Delapouite/kakoune-i3
#
map global user 3 ':enter-user-mode i3<ret>' -docstring 'i3…'

#
# kak-lsp
# https://github.com/ul/kak-lsp
#
eval %sh{kak-lsp --kakoune -s $kak_session}
