#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

sudo true
sudo pacman --sync --refresh --sysupgrade --noconfirm
sudo pacman --sync --needed --noconfirm \
  alacritty \
  bash-language-server \
  cmake \
  direnv \
  docker \
  fd \
  firefox-developer-edition \
  fwupd \
  fzf \
  gimp \
  git \
  gnome \
  gnome-browser-connector \
  htop \
  intellij-idea-community-edition \
  jq \
  krita \
  libreoffice \
  lm_sensors \
  lua-language-server \
  mesa \
  msr-tools \
  neovim \
  prettier \
  pyright \
  python-poetry \
  python-ruff \
  qbittorrent \
  qt6ct \
  shellcheck \
  signal-desktop \
  throttled \
  terraform \
  vlc \
  vscode-json-languageserver \
  vulkan-nouveau \
  wine \
  winetricks \
  xf86-video-intel \
  yaml-language-server \
  zip

yay --sync --needed --noconfirm \
  1password \
  diagnostic-languageserver \
  dockerfile-language-server \
  github-cli \
  lua-format \
  mullvad-vpn \
  tmux-plugin-manager \
  ttf-cascadia-code \
  vim-language-server \
  vim-plug
