#!/usr/bin/env bash
set -eou pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

brew_bundle() {
  subcommand="${1}"
  brew bundle --file "$HOME/.config/homebrew/Brewfile" "${subcommand}"
}

echo "--- Installing and updating brew packages from Brewfile"
brew_bundle check >/dev/null || brew_bundle install
