#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

. ./scripts/lib.bash

arch_packages=(
  bash-completion
  brother-hl-1110
  bitwarden
  bluez
  bluez-utils
  btrfs-progs
  burpsuite
  breeze-gtk
  chromium
  cmake
  compsize
  cups
  cryptsetup
  darktable
  davfs2
  direnv
  dolphin
  dosfstools
  dotnet-runtime
  dotnet-sdk
  efitools
  efibootmgr
  exfat-tools
  fd
  ffmpeg
  ffmpegthumbs
  firefox-developer-edition
  fwupd
  fzf
  gimp
  git
  github-cli
  glxinfo
  gst-plugin-pipewire
  gst-plugin-va
  gst-plugins-good
  helvum
  htop
  httpie
  hunspell-en_au
  hunspell-en_us
  img2pdf
  inetutils
  intel-gpu-tools
  intel-media-driver
  intel-media-sdk
  java-runtime-common
  jdk-openjdk
  jq
  krita
  kdegraphics-thumbnailers
  ldns
  libva-utils
  libvdpau-va-gl
  libreoffice
  linux
  linux-firmware
  lm_sensors
  man-db
  man-pages
  mesa
  msr-tools
  netcat
  nvm
  opentofu
  pacman-contrib
  pandoc
  pdftk
  phonon-qt5-vlc
  phonon-qt6-mpv
  pipewire
  pipewire-pulse
  pipewire-audio
  pipewire-jack
  plasma
  plymouth
  podman
  prettier
  qt6ct
  ripgrep
  rsync
  sddm
  shellcheck
  shfmt
  signal-desktop
  strace
  stylua
  system-config-printer
  syncthing
  tailscale
  texinfo
  texlive-binextra
  texlive-latex
  texlive-latexrecommended
  texlive-fontsrecommended
  throttled
  tree
  ttf-cascadia-code
  ttf-comic-mono-git
  tmux-plugin-manager
  tpm2-tss
  usbutils
  vdpauinfo
  vlc
  vulkan-intel
  vulkan-tools
  lib32-vulkan-intel
  waterfox-bin
  wine
  winetricks
  wireplumber
  wl-clipboard
  yarn
  yt-dlp
  yt-dlg-git
  zip
  zenity
  zoom
)

arch_systemd_services=(
  bluetooth
  cups
  sddm
  NetworkManager
  systemd-boot-update
  systemd-timesyncd
  tailscaled
  throttled
  throttlestop
)

arch_systemd_user_services=(
  pipewire
  pipewire-pulse
  wireplumber
  syncthing
)

log_action "Arch setup script"

log_action "Checking if password is required for sudo"
sudo true

log_action "Checking if reflector is installed"
if ! command -v yay >/dev/null; then
  log "Installing reflector."
  sudo pacman --sync --needed --noconfirm git reflector
else
  log "reflector is installed."
fi

log_action "Updating pacman mirrors with reflector"
sudo reflector \
  --country "AU" \
  --fastest 2 \
  --latest 2 \
  --number 2 \
  --save /etc/pacman.d/mirrorlist

log_action "Checking if yay is installed"
if ! command -v yay >/dev/null; then
  log "Installing yay."
  sudo pacman --sync --needed --noconfirm git base-devel
  mkdir /tmp/yay
  git clone https://aur.archlinux.org/yay.git /tmp/yay
  (
    cd /tmp/yay &&
      makepkg --syncdeps --install --noconfirm
  )
else
  log "yay is already installed."
fi

log_action "System upgrade"
yay --sync --refresh --sysupgrade --noconfirm

log_action "Install packages"
yay --sync --needed --noconfirm "${arch_packages[@]}"

log_action "Update system config files"
for config in $(find_files etc); do
  symlink_as_root "${PWD}/etc/${config}" "/etc/${config}"
done

log_action "Update system scripts"
for script in $(find_files bin); do
  symlink_as_root "${PWD}/bin/${script}" "/usr/local/bin/${script}"
done

log_action "Update user config files"
for config in $(find_files home); do
  symlink "${PWD}/home/${config}" "${HOME}/${config}"
done
for config in $(find_files config/common); do
  symlink "${PWD}/config/common/${config}" "${HOME}/.config/${config}"
done
for config in $(find_files config/arch); do
  symlink "${PWD}/config/arch/${config}" "${HOME}/.config/${config}"
done

log_action "Enable and start systemd services"
for service in "${arch_systemd_services[@]}"; do
  log "Enable systemd service ${service}"
  sudo systemctl enable --now "${service}.service"
done

log_action "Enable and start systemd user services"
for service in "${arch_systemd_user_services[@]}"; do
  log "Enable systemd user service ${service}"
  systemctl --user enable --now "${service}.service"
done

log "Arch setup script complete!"
