#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Packages may be from repositories or the AUR.
arch_packages=( \
  1password \
  alacritty \
  bash-language-server \
  btrfs-progs \
  cmake \
  cups \
  cryptsetup \
  diagnostic-languageserver \
  direnv \
  docker \
  dockerfile-language-server \
  dosfstools \
  efitools \
  efibootmgr \
  exfat-tools \
  fd \
  firefox-developer-edition \
  fwupd \
  fzf \
  gimp \
  git \
  github-cli \
  gnome \
  gnome-browser-connector \
  gnome-shell-extension-dash-to-panel \
  gnome-shell-extension-forge \
  gnome-shell-extension-freon \
  gnome-tweaks \
  godot \
  gst-plugin-pipewire \
  gst-plugins-good \
  helvum \
  htop \
  inetutils 
  intellij-idea-community-edition \
  jq \
  krita \
  ldns \
  lib32-pipewire \
  lib32-pulse \
  libreoffice \
  linux \
  linux-firmware \
  lm_sensors \
  lua-format \
  lua-language-server \
  man-db \
  man-pages \
  mesa \
  msr-tools \
  mullvad-vpn \
  neovim \
  pipewire \
  pipewire-pulse \
  pipewire-audio \
  pipewire-jack \
  plymouth \
  prettier \
  pyright \
  python-poetry \
  python-ruff \
  qbittorrent \
  quodlibet \
  qt6ct \
  ripgrep \
  rsync \
  shellcheck \
  shfmt \
  signal-desktop \
  strace \
  terraform \
  texinfo \
  throttled \
  tree \
  ttf-cascadia-code \
  tmux-plugin-manager \
  tpm2-tss \
  usbutils \
  vim-language-server \
  vlc \
  vscode-json-languageserver \
  vulkan-nouveau \
  wine-staging \
  winetricks \
  wireplumber \
  wl-clipboard
  xf86-video-intel \
  yaml-language-server \
  zip \
  zoom \
  zenity \
)

arch_systemd_services=( \
  cups \
  docker \
  gdm \
  NetworkManager \
  systemd-boot-update \
  systemd-timesyncd \
  throttled \
  throttlestop \
)

arch_systemd_user_services=( \
  pipewire \
  pipewire-pulse \
  wireplumber \
)

log_action() {
  message="${1}"
  echo -en "\033[0;33m---\033[0m "
  echo -e "\033[0;32m${message}\033[0m "
}

log() {
  message="${1}"
  echo -en "\033[0;33m-\033[0m "
  echo -e "\033[0;32m${message}\033[0m"
}

find_files() {
  base_directory="${1}"
  fd \
    --type=file \
    --hidden \
    --base-directory="${base_directory}"
}

diff_and_backup() {
  source="${1}"
  destination="${2}"
  sudo="${3:-false}"
  sudo_prefix=
  [[ "${sudo}" =~ ^(true|on|1)$ ]] && sudo_prefix=sudo
  log "Diff source to ${destination}"
  if ${sudo_prefix} diff "${source}" "${destination}"; then
    log "${destination} is unchanged."
    return 0
  else
    log "${destination} will change."
    log "Create directories along $(dirname "${destination}")"
    ${sudo_prefix} mkdir -p "$(dirname "${destination}")"
    log "Backup ${destination} to ${destination}.bak"
    ${sudo_prefix} cp "${destination}" "${destination}.bak"
    return 1
  fi
}

copy() {
  source="${1}"
  destination="${2}"
  sudo="${3:-false}"
  sudo_prefix=
  [[ "${sudo}" =~ ^(true|on|1)$ ]] && sudo_prefix=sudo
  if ! diff_and_backup "${source}" "${destination}" "${sudo}"; then
    log "Copy ${source} to ${destination}"
    ${sudo_prefix} cp "${source}" "${destination}"
  fi
}

copy_as_root() {
  source="${1}"
  destination="${2}"
  copy "${source}" "${destination}" "true"
}

log_action "Arch setup script"

log_action "Checking if password is required for sudo"
sudo true

log_action "Checking if reflector is installed"
if ! command -v yay > /dev/null; then
  log "Installing reflector."
  sudo pacman --sync --needed --noconfirm git reflector
else
  log "reflector is installed."
fi

log_action "Updating pacman mirrors with reflector"
sudo reflector \
  --country "AU" \
  --fastest 6 \
  --latest 6 \
  --number 6 \
  --save /etc/pacman.d/mirrorlist

log_action "Checking if yay is installed"
if ! command -v yay > /dev/null; then
  log "Installing yay."
  sudo pacman --sync --needed --noconfirm git base-devel
  mkdir /tmp/yay
  git clone https://aur.archlinux.org/yay.git /tmp/yay
  (
    cd /tmp/yay && \
      makepkg --syncdeps --install --noconfirm
  )
else
  log "yay is already installed."
fi

log_action "System upgrade"
yay --sync --refresh --sysupgrade --noconfirm

log_action "Install packages"
yay --sync --needed --noconfirm "${arch_packages[@]}"

log_action "Update system config files"
for config in $(find_files etc); do
  copy_as_root "${PWD}/etc/${config}" "/etc/${config}"
done

log_action "Update system scripts"
for script in $(find_files bin); do
  copy_as_root "${PWD}/bin/${script}" "/usr/local/bin/${script}"
done

log_action "Update user config files"
for config in $(find_files home); do
  copy "${PWD}/home/${config}" "${HOME}/${config}"
done
for config in $(find_files config); do
  copy "${PWD}/config/${config}" "${HOME}/.config/${config}"
done

log_action "Enable and start systemd services"
for service in "${arch_systemd_services[@]}"; do
  log "Enable systemd service ${service}"
  sudo systemctl enable --now "${service}.service"
done

log_action "Enable and start systemd user services"
for service in "${arch_systemd_user_services[@]}"; do
  log "Enable systemd user service ${service}"
  sudo systemctl --user enable --now "${service}.service"
done

log "Arch setup script complete!"
